### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by gunta** [rstacruz/mocha-standard#1]
Hi!

By default, usually the tests done by `mocha-standard` take more than 2 seconds on first run, even if its a single file being tested, which makes it error with 

```
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

It would be nice to change the README to reflect that either using done or timeout.

**Comment by rstacruz** [comment]
yeah, i noticed that after a while too

**Comment by rstacruz** [comment]
done!
